const menu = [
    {
        name: "",
        image: "",
        type: "",
        price: "",
        popularity: "",
    },
    {
        name: "",
        image: "",
        type: "",
        price: "",
        popularity: "",
    },
    {
        name: "",
        image: "",
        type: "",
        price: "",
        popularity: "",
    },
    {
        name: "",
        image: "",
        type: "",
        price: "",
        popularity: "",
    },
    {
        name: "",
        image: "",
        type: "",
        price: "",
        popularity: "",
    },
    {
        name: "",
        image: "",
        type: "",
        price: "",
        popularity: "",
    },
    {
        name: "",
        image: "",
        type: "",
        price: "",
        popularity: "",
    },
    {
        name: "",
        image: "",
        type: "",
        price: "",
        popularity: "",
    },
    {
        name: "",
        image: "",
        type: "",
        price: "",
        popularity: "",
    },
    {
        name: "",
        image: "",
        type: "",
        price: "",
        popularity: "",
    },
    {
        name: "",
        image: "",
        type: "",
        price: "",
        popularity: "",
    },
    {
        name: "",
        image: "",
        type: "",
        price: "",
        popularity: "",
    },
    {
        name: "",
        image: "",
        type: "",
        price: "",
        popularity: "",
    },
]
export {menu};
